/* tslint:disable */
// api v0.1.0 57299421d7d9aa1e9a85f991b5130fd875b0939a
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.1.0"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "57299421d7d9aa1e9a85f991b5130fd875b0939a"


//
// Types
//
export interface Version {
  webrpcVersion: string
  schemaVersion: string
  schemaHash: string
  appVersion: string
}

export interface SuggestedGasPrice {
  blockNum: number
  blockTime: number
  rapid: number
  fast: number
  standard: number
  slow: number
}

export interface ETHGas {
  ping(headers?: object): Promise<PingReturn>
  version(headers?: object): Promise<VersionReturn>
  suggestedGasPrice(headers?: object): Promise<SuggestedGasPriceReturn>
  history(headers?: object): Promise<HistoryReturn>
}

export interface PingArgs {
}

export interface PingReturn {
  ok: boolean  
}
export interface VersionArgs {
}

export interface VersionReturn {
  version: Version  
}
export interface SuggestedGasPriceArgs {
}

export interface SuggestedGasPriceReturn {
  suggestedGasPrice: SuggestedGasPrice  
}
export interface HistoryArgs {
}

export interface HistoryReturn {
  data: {[key: number]: Array<number>}  
}


  
//
// Client
//
export class ETHGas implements ETHGas {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/ETHGas/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  ping = (headers?: object): Promise<PingReturn> => {
    return this.fetch(
      this.url('Ping'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          ok: <boolean>(_data.ok)
        }
      })
    })
  }
  
  version = (headers?: object): Promise<VersionReturn> => {
    return this.fetch(
      this.url('Version'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          version: <Version>(_data.version)
        }
      })
    })
  }
  
  suggestedGasPrice = (headers?: object): Promise<SuggestedGasPriceReturn> => {
    return this.fetch(
      this.url('SuggestedGasPrice'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          suggestedGasPrice: <SuggestedGasPrice>(_data.suggestedGasPrice)
        }
      })
    })
  }
  
  history = (headers?: object): Promise<HistoryReturn> => {
    return this.fetch(
      this.url('History'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          data: <{[key: number]: Array<number>}>(_data.data)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
